language: php

env:
  - DBTYPE=mysql
  - DBTYPE=sqlite
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - bash ./build/travis/before_script.sh

script:
  - bash ./build/travis/script.sh

after_success:
  - bash ./build/travis/after_script.sh

